/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace OreWars {
  export type AgentStruct = {
    owner: AddressLike;
    agentId: string;
    totalMined: BigNumberish;
    rocksMined: BigNumberish;
    active: boolean;
  };

  export type AgentStructOutput = [
    owner: string,
    agentId: string,
    totalMined: bigint,
    rocksMined: bigint,
    active: boolean
  ] & {
    owner: string;
    agentId: string;
    totalMined: bigint;
    rocksMined: bigint;
    active: boolean;
  };

  export type RockStruct = {
    hasOre: boolean;
    oreAmount: BigNumberish;
    mined: boolean;
    minedByAgent: string;
  };

  export type RockStructOutput = [
    hasOre: boolean,
    oreAmount: bigint,
    mined: boolean,
    minedByAgent: string
  ] & {
    hasOre: boolean;
    oreAmount: bigint;
    mined: boolean;
    minedByAgent: string;
  };
}

export interface OreWarsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agents"
      | "claimOre"
      | "gameServer"
      | "getAgent"
      | "getRock"
      | "mapEpoch"
      | "owner"
      | "prizePool"
      | "registerAgent"
      | "renounceOwnership"
      | "resetMap"
      | "rocks"
      | "seedRock"
      | "setGameServer"
      | "transferOwnership"
      | "withdrawUnused"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "MapReset"
      | "OwnershipTransferred"
      | "PoolFunded"
      | "RockMined"
  ): EventFragment;

  encodeFunctionData(functionFragment: "agents", values: [string]): string;
  encodeFunctionData(
    functionFragment: "claimOre",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gameServer",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getAgent", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getRock",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "mapEpoch", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "prizePool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "resetMap", values?: undefined): string;
  encodeFunctionData(functionFragment: "rocks", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "seedRock",
    values: [BigNumberish, BigNumberish, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGameServer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawUnused",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimOre", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gameServer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mapEpoch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "prizePool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resetMap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rocks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "seedRock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setGameServer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawUnused",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [agentId: string, owner: AddressLike];
  export type OutputTuple = [agentId: string, owner: string];
  export interface OutputObject {
    agentId: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MapResetEvent {
  export type InputTuple = [newEpoch: BigNumberish];
  export type OutputTuple = [newEpoch: bigint];
  export interface OutputObject {
    newEpoch: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolFundedEvent {
  export type InputTuple = [from: AddressLike, amount: BigNumberish];
  export type OutputTuple = [from: string, amount: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RockMinedEvent {
  export type InputTuple = [
    agentId: string,
    x: BigNumberish,
    y: BigNumberish,
    hadOre: boolean,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    agentId: string,
    x: bigint,
    y: bigint,
    hadOre: boolean,
    amount: bigint
  ];
  export interface OutputObject {
    agentId: string;
    x: bigint;
    y: bigint;
    hadOre: boolean;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OreWars extends BaseContract {
  connect(runner?: ContractRunner | null): OreWars;
  waitForDeployment(): Promise<this>;

  interface: OreWarsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agents: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, bigint, boolean] & {
        owner: string;
        agentId: string;
        totalMined: bigint;
        rocksMined: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  claimOre: TypedContractMethod<
    [agentId: string, x: BigNumberish, y: BigNumberish],
    [void],
    "nonpayable"
  >;

  gameServer: TypedContractMethod<[], [string], "view">;

  getAgent: TypedContractMethod<
    [agentId: string],
    [OreWars.AgentStructOutput],
    "view"
  >;

  getRock: TypedContractMethod<
    [x: BigNumberish, y: BigNumberish],
    [OreWars.RockStructOutput],
    "view"
  >;

  mapEpoch: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  prizePool: TypedContractMethod<[], [bigint], "view">;

  registerAgent: TypedContractMethod<
    [agentId: string, owner: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resetMap: TypedContractMethod<[], [void], "nonpayable">;

  rocks: TypedContractMethod<
    [arg0: BytesLike],
    [
      [boolean, bigint, boolean, string] & {
        hasOre: boolean;
        oreAmount: bigint;
        mined: boolean;
        minedByAgent: string;
      }
    ],
    "view"
  >;

  seedRock: TypedContractMethod<
    [
      x: BigNumberish,
      y: BigNumberish,
      hasOre: boolean,
      oreAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setGameServer: TypedContractMethod<
    [_gameServer: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawUnused: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, bigint, boolean] & {
        owner: string;
        agentId: string;
        totalMined: bigint;
        rocksMined: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimOre"
  ): TypedContractMethod<
    [agentId: string, x: BigNumberish, y: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gameServer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agentId: string],
    [OreWars.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRock"
  ): TypedContractMethod<
    [x: BigNumberish, y: BigNumberish],
    [OreWars.RockStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "mapEpoch"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "prizePool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [agentId: string, owner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resetMap"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rocks"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [boolean, bigint, boolean, string] & {
        hasOre: boolean;
        oreAmount: bigint;
        mined: boolean;
        minedByAgent: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "seedRock"
  ): TypedContractMethod<
    [
      x: BigNumberish,
      y: BigNumberish,
      hasOre: boolean,
      oreAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setGameServer"
  ): TypedContractMethod<[_gameServer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawUnused"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "MapReset"
  ): TypedContractEvent<
    MapResetEvent.InputTuple,
    MapResetEvent.OutputTuple,
    MapResetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PoolFunded"
  ): TypedContractEvent<
    PoolFundedEvent.InputTuple,
    PoolFundedEvent.OutputTuple,
    PoolFundedEvent.OutputObject
  >;
  getEvent(
    key: "RockMined"
  ): TypedContractEvent<
    RockMinedEvent.InputTuple,
    RockMinedEvent.OutputTuple,
    RockMinedEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(string,address)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "MapReset(uint256)": TypedContractEvent<
      MapResetEvent.InputTuple,
      MapResetEvent.OutputTuple,
      MapResetEvent.OutputObject
    >;
    MapReset: TypedContractEvent<
      MapResetEvent.InputTuple,
      MapResetEvent.OutputTuple,
      MapResetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PoolFunded(address,uint256)": TypedContractEvent<
      PoolFundedEvent.InputTuple,
      PoolFundedEvent.OutputTuple,
      PoolFundedEvent.OutputObject
    >;
    PoolFunded: TypedContractEvent<
      PoolFundedEvent.InputTuple,
      PoolFundedEvent.OutputTuple,
      PoolFundedEvent.OutputObject
    >;

    "RockMined(string,uint256,uint256,bool,uint256)": TypedContractEvent<
      RockMinedEvent.InputTuple,
      RockMinedEvent.OutputTuple,
      RockMinedEvent.OutputObject
    >;
    RockMined: TypedContractEvent<
      RockMinedEvent.InputTuple,
      RockMinedEvent.OutputTuple,
      RockMinedEvent.OutputObject
    >;
  };
}
